# Generated by Django 2.2.28 on 2022-05-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_recipes', '0002_auto_20220524_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ['-recipe'], 'verbose_name': 'Ингредиенты в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
    ]
